language: python

python:
    - "2.7"

sudo: false

#before_install:
#    - sudo add-apt-repository ppa:fenics-packages/fenics -y
#    - sudo apt-get update
#    - sudo apt-get install fenics
  
#virtualenv:
#    system_site_packages: true
        
install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION Cython mpi4py scipy pytest sympy
    #- export PYTHONPATH="/usr/lib/python2.7/dist-packages/dolfin:$PYTHONPATH"
    - conda create --name fenics27 python=2.7
    - source activate fenics27
    - conda install fenics --channel juanlu001    
    
    - wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.16.tar
    - export HDFHOME=$HOME/hdf5-1.8.16
    - tar -xvf hdf5-1.8.16.tar
    - cd hdf5-1.8.16 && ./configure --enable-parallel --enable-shared && make -j4 && make install
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HDFHOME/hdf5
    - export CC=mpicc
    - pip install -r requirements.txt
    - wget https://github.com/h5py/h5py/archive/2.6.0.tar.gz
    - tar -xzvf 2.6.0.tar.gz
    - cd h5py-2.6.0 && python setup.py configure --mpi --hdf5=$HDFHOME/hdf5 && python setup.py build && python setup.py install && cd ..
    - export PYTHONPATH="$HOME/lib/python2.7/site-packages:$PYTHONPATH";
    - python setup.py install

after_failure:
    - cd $HOME/.instant/error
    - bash /home/travis/build/mikaem/fenicstools/tests/print_compilelog.sh

script:
    - cd $PWD/tests; py.test
