language: generic

os: osx
osx_image: xcode9.2

sudo: false

env:

  matrix:
    - CONDA_PY=37

  global:
    - FENICS_VERSION="2019.1.0"
    - secure: "FsaxTWmCYU8spBD/dlo7ZOEV801Wivdop8JkosJTnGxbfbIiyN6naSfflrm9d8vKPKvSB7ics+QVr4s0dZ2f/jT0o0GdCqUr7hgeSeprUtWlZHBNMVggZIp1Dke7Y4gLgOJ5Jwg8hRkn3pzClip54nFqwSqEuS9gSuKzsQbNVMM="

before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --set always_yes yes
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install -n root conda-build

script:
    - conda build conf/conda

after_success:
    - |
      source /Users/travis/miniconda3/bin/activate root
      anaconda upload -t $BINSTAR_TOKEN -u mikaem -c main --skip-existing ~/miniconda3/conda-bld/osx-64/*.tar.bz2
