language: python

python:
    - "2.7"

before_install:
    - sudo add-apt-repository ppa:fenics-packages/fenics -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq fenics
    - sudo apt-get install openmpi-bin openmpi-dev
    
#virtualenv:
#    system_site_packages: true

install:
    - export PYTHONPATH="/usr/lib/python2.7/dist-packages/dolfin:$PYTHONPATH"
    - export CC=mpicc
    - pip install -r requirements.txt
    - which mpirun
    - python setup.py install
        
script:
    - cd $PWD/tests; py.test