language: python

python:
    - "2.7"

sudo: false

#before_install:
#    - sudo add-apt-repository ppa:fenics-packages/fenics -y
#    - sudo apt-get update
#    - sudo apt-get install fenics
  
#virtualenv:
#    system_site_packages: true
        
install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - unset PYTHONPATH
    #- unset LD_LIBRARY_PATH
    #- unset DYLD_LIBRARY_PATH
    - conda config --set always_yes yes 
    - conda install h5py --channel mikaem
    - conda install fenics --channel mikaem/label/dev mikaem
    - conda install pyvtk mpi4py hwloc --channel mikaem
    - conda install pytest
    - ldd $HOME/miniconda/lib/libdolfin.so
    #- wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.16.tar
    #- export HDFHOME=`pwd`/hdf5-1.8.16
    #- tar -xvf hdf5-1.8.16.tar
    #- cd hdf5-1.8.16 && ./configure --enable-parallel --enable-shared && make -j4 && make install && cd ..
    #- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HDFHOME/hdf5
    #- export CC=mpicc
    #- pip install -r requirements.txt
    #- wget https://github.com/h5py/h5py/archive/2.6.0.tar.gz
    #- tar -xzvf 2.6.0.tar.gz
    #- cd h5py-2.6.0 && python setup.py configure --mpi --hdf5=$HDFHOME/hdf5 && python setup.py build_ext --include-dirs=$HDFHOME/hdf5/include && python setup.py install && cd ..
    #- cd h5py-2.6.0 && python setup.py configure --mpi && python setup.py build_ext && python setup.py install && cd ..
    #- export PYTHONPATH="$HOME/lib/python2.7/site-packages:$PYTHONPATH";
    - python setup.py install

after_failure:
    - cd $HOME/.instant/error
    - bash /home/travis/build/mikaem/fenicstools/tests/print_compilelog.sh

script:
    - cd $PWD/tests; py.test
