language: python

python:
    - "2.7"

#sudo: false

#before_install:
#    - sudo add-apt-repository ppa:fenics-packages/fenics -y
#    - sudo apt-get update
#    - sudo apt-get install fenics
  
#virtualenv:
#    system_site_packages: true

install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - unset PYTHONPATH
    - conda config --set always_yes yes 
    - conda config --add channels mikaem/label/test
    - conda config --add channels mikaem
    - conda install mpi4py fenics=1.7.0 pyvtk h5py=2.6.0 hwloc pytest boost=1.57.0
    - python setup.py install

after_failure:
    - cd $HOME/.instant/error
    - bash /home/travis/build/mikaem/fenicstools/tests/print_compilelog.sh

script:
    - cd $PWD/tests; py.test
