language: python

python:
    - "2.7"

sudo: false

before_install:
    - sudo add-apt-repository ppa:fenics-packages/fenics -y
    - sudo apt-get update
    - sudo apt-get install fenics
    
virtualenv:
    system_site_packages: true

install:
    - export PYTHONPATH="/usr/lib/python2.7/dist-packages/dolfin:$PYTHONPATH"
    - export CC=mpicc
    - pip install -r requirements.txt
    - wget https://github.com/h5py/h5py/archive/2.6.0.tar.gz
    - tar -xzvf 2.6.0.tar.gz
    - cd h5py-2.6.0 && python setup.py configure --mpi && python setup.py build && python setup.py install && cd ..
    - export PYTHONPATH="$HOME/lib/python2.7/site-packages:$PYTHONPATH";
    - python setup.py install

after_failure:
    - cd $HOME/.instant/error
    - bash /home/travis/build/mikaem/fenicstools/tests/print_compilelog.sh

script:
    - cd $PWD/tests; py.test
