language: python

python:
    - "2.7"

before_install:
    - sudo add-apt-repository ppa:fenics-packages/fenics -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq fenics
    
virtualenv:
    system_site_packages: true

install:
    - export PYTHONPATH="/usr/lib/python2.7/dist-packages/dolfin:$PYTHONPATH"
    - export CC=mpicc
    - pip install -r requirements.txt
    - locate libhdf5
    - wget https://github.com/h5py/h5py/archive/2.5.0.tar.gz
    - tar -xzvf 2.5.0.tar.gz
    - cd h5py-2.5.0 && python setup.py configure --mpi && python setup.py build && python setup.py install
    - export PYTHONPATH="$HOME/lib/python2.7/site-packages:$PYTHONPATH";
    - python setup.py install
        
script:
    - cd $PWD/tests; py.test