language: python

python:
    - "2.7"

sudo: required

before_install:
    #- sudo add-apt-repository ppa:fenics-packages/fenics -y
    #- sudo apt-get update
    #- sudo apt-get install fenics
    #- sudo apt-get install gfortran build-essential freeglut3-dev
    #- export FENICS_INSTALL_BUILD_TYPE=0
    #- curl -s http://fenicsproject.org/fenics-install.sh | bash
    - sudo apt-get update -qq
    - sudo apt-get install gfortran pv
    - sudo apt-get install cmake libopenmpi-dev python-dev libblas-dev liblapack-dev wget libboost-program-options1.48-dev libboost-filesystem1.48-dev libboost-serialization1.48-dev libboost-thread1.48-dev libboost-iostreams1.48-dev libboost-math1.48-dev libboost-timer1.48-dev libboost-chrono1.48-dev
  
virtualenv:
    system_site_packages: true
    
install:
    #- export PYTHONPATH="/usr/lib/python2.7/dist-packages/dolfin:$PYTHONPATH"
    #- export PYTHONPATH="$HOME/lib/python2.7/site-packages/dolfin:$PYTHONPATH"
    - git clone https://github.com/hashdist/hashdist.git
    - git clone https://github.com/hashdist/hashstack.git
    - cp hashstack/tests/test.dolfin.yaml .
    - ./hashdist/bin/hit init-home
    - export PATH=`pwd`/hashdist/bin:$PATH
    - set -o pipefail    
    - hit build -v test.dolfin.yaml
    - export CC=mpicc
    - pip install -r requirements.txt
    - wget https://github.com/h5py/h5py/archive/2.6.0.tar.gz
    - tar -xzvf 2.6.0.tar.gz
    - cd h5py-2.6.0 && python setup.py configure --mpi && python setup.py build && python setup.py install && cd ..
    - export PYTHONPATH="$HOME/lib/python2.7/site-packages:$PYTHONPATH";
    - python setup.py install

after_failure:
    - cd $HOME/.instant/error
    - bash /home/travis/build/mikaem/fenicstools/tests/print_compilelog.sh

script:
    - cd $PWD/tests; py.test
