package:
  name: fenicstools
  version: {{FENICS_VERSION}}

source:
  git_url: ../../

build:
  number: 3

requirements:
  build:
    - fenics =={{FENICS_VERSION}}
    - pip
    #- pyvtk
    #- h5py-parallel

  run:
    - fenics =={{FENICS_VERSION}}
    #- pyvtk
    #- h5py-parallel
    - mpi4py

test:
  source_files:
    - tests

  requires:
    - pytest

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
