{% set version = "2019.1.0" %}

package:
  name: fenicstools
  version: {{ version }}

source:
  git_url: ../../

build:
  number: 0

requirements:
  host:
    - python
    - fenics =={{ version }}
    - pip

  run:
    - python
    - fenics =={{ version }}
    - mpi4py

test:
  source_files:
    - tests

  requires:
    - pytest

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
