package:
  name: fenicstools
  version: {{FENICS_VERSION}}

source:
  git_url: ../../

build:
  number: 2

requirements:
  build:
    - fenics =={{FENICS_VERSION}}
    - pyvtk
    - h5py-parallel

  run:
    - fenics =={{FENICS_VERSION}}
    - pyvtk
    - mpi4py
    - h5py-parallel

test:
  source_files:
    - tests

  requires:
    - pytest

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
