package:
  name: fenicstools
  version: {{FENICS_VERSION}}

source:
  git_url: ../../

build:
  number: 1

requirements:
  build:
    - fenics =={{FENICS_VERSION}}
    - pyvtk
    - openblas
    - h5py-parallel

  run:
    - fenics =={{FENICS_VERSION}}
    - pyvtk
    - mpi4py
    - openblas
    - h5py-parallel

test:
    requires:
      - fenics =={{FENICS_VERSION}}
      - pyvtk
      - h5py-parallel
      - pytest

    #imports:
      #- dolfin
      #- fenicstools


# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
